Docker
jackfrost373/LHCb_Xic_production pull request #89
Opened 2022-04-13 14:56 UTC by FelixRitter3110

2022-04-13 14:57 UTC, FelixRitter3110 commented
Okay Im a bit suprised why all the commits from my other branch landed here as well?
Anyway first commit for addition of dockerfile.
Supports CCentOS7 base image and snakemake.

2022-04-14 07:24 UTC, cpawley requested changes
I think you should close this MR and make a freshone with only the docker stuff

2022-04-14 07:24 UTC, cpawley commented on analysis/Scripts/Docker/dockerfile
> +LABEL maintainer.email="fritter@student.maastrichtuniversity.nl"
missing .

2022-04-14 07:24 UTC, cpawley commented on analysis/Scripts/Docker/packages
> +R
are all of these really needed?

2022-04-14 09:52 UTC, FelixRitter3110 commented on analysis/Scripts/Docker/dockerfile
> +LABEL maintainer.email="fritter@student.maastrichtuniversity.nl"
resolved

2022-04-16 11:35 UTC, closed without merging

2022-04-16 11:36 UTC, FelixRitter3110 commented
as discussed docker commit will be on separate branch